### ISSUE TITLE
VS 2015 compilation issue

### ISSUE THREAD

**Issue by hypeartist** [Zplutor/zaf#1]
I get the error while trying to compile the project in VS 2015:

file: **propert_map.h**
line: **39**

``` cpp
iterator = properties_.insert(std::make_pair(property_name, default_property)).first;
```

resulted in:

```
c:\program files (x86)\microsoft visual studio 14.0\vc\include\utility(329): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to '_Mypair'
```

---

```
c:\program files (x86)\microsoft visual studio 14.0\vc\include\utility(329): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

---

```
d:\allthatjazz\vs\projects\zaf-master\src\zaf\base\property_map.h(39): note: see reference to function template instantiation 'std::pair<std::wstring,PropertyType> std::make_pair<const std::wstring&,PropertyType&>(_Ty1,_Ty2)' being compiled
          with
          [
              PropertyType=zaf::ClickableControl::ClickEvent,
              _Ty1=const std::wstring &,
              _Ty2=zaf::ClickableControl::ClickEvent &
          ]
```

I'm not a big C++ expert so could you please help me with this.
Regards.

**Comment by fatvlady** [comment]
Probably, `default_property` doesn't have a copy constructor. You should make second pair type reference type, for example, create `std::pair<std::wsting, zaf::ClickableControl::ClickEvent &>` instead of calling `make_pair`, since the latter dereferences type.

**Comment by Zplutor** [comment]
Sorry, I notice this issue just now...
This problem has been fixed in previous updates, you can update the codes, and try it again.
